[alembic]
script_location = server/db/migrations
prepend_sys_path = .
# Используем синхронный драйвер psycopg2 вместо asyncpg
sqlalchemy.url = postgresql://user:J73ZyKfifH8x1AB4kYuNWvrQ9K6OA5VZ@dpg-d4iurf15pdvs7385ojl0-a.oregon-postgres.render.com/industrial_site_design_system

file_template = %%(rev)s_%%(slug)s

[post_write_hooks]
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
